version: "3.9"
services:
  rethinkdb-1:
    image: rethinkdb:2.4
    volumes:
      - rethinkdb-1-data:/data
    ports:
      - "8080:8080"
      - "28015:28015"
      - "29015:29015"
    environment:
      - DB_NAME=ci-connector-transaction
    networks:
      - rethinkdb-net
  rethinkdb-2:
    image: rethinkdb:2.4
    volumes:
      - rethinkdb-2-data:/data
    ports:
      - "8081:8080"
      - "28017:28015"
      - "29017:29015"
    environment:
      - DB_NAME=ci-connector-transaction
    networks:
      - rethinkdb-net
  # rethinkdb:
  #   image: rethinkdb:2.4
  #   ports:
  #     - 8080:8080
  #   volumes:
  #     - ~/apps/rethinkdb/data:/app
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
  db:
    container_name: pg_container
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: bifast_db
    ports:
      - "5432:5432"
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: raj@nola.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
  
volumes:
  rethinkdb-1-data:
  rethinkdb-2-data:

networks:
  rethinkdb-net:
   